name: Deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          
      - name: Build
        run: |
          npm run build
        env:
          VITE_API_URL: 'https://tech0-gen-8-step4-eyesmile-back.azurewebsites.net'

      - name: Prepare for deployment
        run: |
          mkdir -p deploy
          cp -r dist/* deploy/
          echo '<?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <location path="index.html">
              <system.webServer>
                <httpProtocol>
                  <customHeaders>
                    <add name="Cache-Control" value="no-cache" />
                  </customHeaders>
                </httpProtocol>
              </system.webServer>
            </location>
            <system.webServer>
              <staticContent>
                <remove fileExtension=".js" />
                <remove fileExtension=".css" />
                <remove fileExtension=".json" />
                <remove fileExtension=".html" />
                <mimeMap fileExtension=".js" mimeType="application/javascript" />
                <mimeMap fileExtension=".css" mimeType="text/css" />
                <mimeMap fileExtension=".json" mimeType="application/json" />
                <mimeMap fileExtension=".html" mimeType="text/html" />
                <mimeMap fileExtension="." mimeType="text/html" />
              </staticContent>
              <rewrite>
                <rules>
                  <rule name="SPA" enabled="true" stopProcessing="true">
                    <match url="^(?!.*\.(js|css|json|png|jpg|ico|svg)).*$" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.html" />
                  </rule>
                </rules>
              </rewrite>
              <httpErrors errorMode="Custom" defaultResponseMode="ExecuteURL">
                <remove statusCode="404" />
                <error statusCode="404" path="/index.html" responseMode="ExecuteURL" />
              </httpErrors>
            </system.webServer>
          </configuration>' > deploy/web.config
          echo '{ "platform": "static" }' > deploy/.deployment

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tech0-gen-8-step4-eyesmile'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F90906F5F2994C96800591BC6F0D61C5 }}
          package: deploy 