name: Deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Repository structure:"
          tree || (apt-get update && apt-get install -y tree && tree)

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -d "EyeSmile/frontend" ]; then
            cd EyeSmile/frontend
          elif [ -d "frontend" ]; then
            cd frontend
          else
            echo "Error: Frontend directory not found"
            exit 1
          fi
          npm install --force
          
      - name: Build
        run: |
          if [ -d "EyeSmile/frontend" ]; then
            cd EyeSmile/frontend
          elif [ -d "frontend" ]; then
            cd frontend
          fi
          npm run build
        env:
          VITE_API_URL: 'https://tech0-gen-8-step4-eyesmile-back.azurewebsites.net'
        
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./frontend"
          output_location: "dist"
          skip_app_build: false
