name: Deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          
      - name: Build
        run: |
          npm run build
        env:
          VITE_API_URL: 'https://tech0-gen-8-step4-eyesmile-back.azurewebsites.net'

      - name: Add deployment files
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <staticContent>
                <remove fileExtension=".js" />
                <remove fileExtension=".json" />
                <remove fileExtension=".css" />
                <mimeMap fileExtension=".js" mimeType="application/javascript" />
                <mimeMap fileExtension=".json" mimeType="application/json" />
                <mimeMap fileExtension=".css" mimeType="text/css" />
              </staticContent>
              <rewrite>
                <rules>
                  <rule name="Routes" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.html" />
                  </rule>
                </rules>
              </rewrite>
            </system.webServer>
          </configuration>' > dist/web.config
          echo '# startup command
          WEBSITES_PORT=8080' > dist/.env
          echo 'const express = require("express");
          const path = require("path");
          const app = express();
          app.use(express.static(path.join(__dirname)));
          app.get("*", (req, res) => {
            res.sendFile(path.join(__dirname, "index.html"));
          });
          const port = process.env.WEBSITES_PORT || 8080;
          app.listen(port, () => {
            console.log(`Server is running on port ${port}`);
          });' > dist/server.js
          echo '{
            "name": "eyesmile-frontend",
            "version": "1.0.0",
            "private": true,
            "scripts": {
              "start": "node server.js"
            },
            "dependencies": {
              "express": "^4.18.2"
            }
          }' > dist/package.json
          cd dist && npm install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tech0-gen-8-step4-eyesmile'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F90906F5F2994C96800591BC6F0D61C5 }}
          package: dist 