name: Deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          
      - name: Build
        run: |
          npm run build
        env:
          VITE_API_URL: 'https://tech0-gen-8-step4-eyesmile-back.azurewebsites.net'

      - name: Prepare for deployment
        run: |
          mkdir -p deploy
          cp -r dist/* deploy/
          echo '<?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name="StaticFile" path="*" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
              </handlers>
              <staticContent>
                <remove fileExtension=".js" />
                <remove fileExtension=".css" />
                <remove fileExtension=".json" />
                <mimeMap fileExtension=".js" mimeType="application/javascript" />
                <mimeMap fileExtension=".css" mimeType="text/css" />
                <mimeMap fileExtension=".json" mimeType="application/json" />
              </staticContent>
              <rewrite>
                <rules>
                  <rule name="SPA" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/" />
                  </rule>
                </rules>
              </rewrite>
            </system.webServer>
          </configuration>' > deploy/web.config

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tech0-gen-8-step4-eyesmile'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F90906F5F2994C96800591BC6F0D61C5 }}
          package: deploy 